# Generated by Django 4.2.7 on 2023-11-29 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_focusroom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='focusroom',
        ),
    ]
